import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useQuery } from "react-query";
import styles from "../styles/Home.module.css";
import axios from "axios";

// const maindata = async () => {
//   try {
//       // const { data } = await axios.get("http://localhost:3000/api/todo")
//       // console.log(data)
//       // let data ;
//       const data = await fetch("http://localhost:3000/api/todo")
//       .then((res) => res.json())
//       .then((res) => res)
//       // console.log(data)
//       return data
//       }
//    catch (err) {
//     return err
//   }
// }

export default function Home({ dat }) {
  const [data, setDate] = useState([]);
  const [title, settitle] = useState("");
  const [desc, setdesc] = useState("");

  // const {data, isLoading, isError} =  useQuery("fetchdata" , maindata)
  // console.log(data, isLoading,isError)

  const handleAddtodo = () => {
    let payload = {
      title: title,
      description: desc,
      status: false,
    };
    fetch("api/todo", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    })
      .then((res) => {
        display();
        alert("tasks add suscessfully");
      })
      .catch((err) => console.log("something went wrong" + err));
  };
  const handleDelete = (id) => {
    fetch("api/todo", {
      method: "DELETE",
      body: id,
    })
      .then((res) => {
        alert("delete suscessfully");
        display();
      })
      .catch((err) => console.log("something went wrong" + err));
  };

  const display = () => {
    fetch("api/todo")
      .then((res) => res.json())
      .then((res) => setDate(res));
  };

  const toggal = (id, status) => {
    let check = status === false ? true : false;
    const payload = {
      _id: id,
      status: check,
    };
    fetch("api/todo", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    })
      .then((res) => {
        display();
        console.log("updated successfully");
      })
      .catch((err) => console.log("error occurred" + err));
  };

  useEffect(() => {
    display();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <style jsx>{``}</style>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Todo</h1>

        <div className={styles.grid}>
          <div>
            <p>Title</p>
            <input
              type="text"
              placeholder="enter task hare"
              onChange={(e) => settitle(e.target.value)}
            />
          </div>
          <div>
            <p>Description</p>
            <input
              type="text"
              placeholder="enter description hare"
              onChange={(e) => setdesc(e.target.value)}
            />
          </div>
          <div>
            <button className={styles.submit} onClick={handleAddtodo}>
              Submit
            </button>
          </div>
        </div>
        {data.map((el) => {
          return (
            <div className={styles.description} key={el._id}>
              <p>{el.title}</p>
              <input defaultValue={el.description} />
              <button
                onClick={() => toggal(el._id, el.status, el.title)}
                className={styles.btn}
              >{`${el.status ? "Done" : "Not Done"}`}</button>
              <button
                className={styles.btn}
                onClick={() => handleDelete(el._id)}
              >
                Delete
              </button>
            </div>
          );
        })}
      </main>
    </div>
  );
}

// ----------------static render------------------------

// export async function getStaticProps(){
//   const res = await fetch("http://localhost:3000/api/todo")
//   const data = await res.json();
//   return {
//     props:{
//       data,
//     },
//   }
// }


// --------------------------- serverSide render ---------------

// export async function getServerSideProps(){
//   const res = await fetch("http://localhost:3000/api/todo")
//   const data = await res.json();
//   return {
//     props:{
//       data,
//     },
//   }
// }
